Infos] Launching headless browser...
Traceback (most recent call last):
  File "/home/lazarus/ProxyCrawler/proxy_scraper.py", line 62, in <module>
    proxies = fetch_live_proxies_selenium()
  File "/home/lazarus/ProxyCrawler/proxy_scraper.py", line 14, in fetch_live_proxies_selenium
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)
  File "/home/lazarus/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/lazarus/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/lazarus/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/home/lazarus/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/lazarus/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/home/lazarus/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x6362d17bd4e3 <unknown>
#1 0x6362d14ecc76 <unknown>
#2 0x6362d1513757 <unknown>
#3 0x6362d1512029 <unknown>
#4 0x6362d1550ccc <unknown>
#5 0x6362d155047f <unknown>
#6 0x6362d1547de3 <unknown>
#7 0x6362d151d2dd <unknown>
#8 0x6362d151e34e <unknown>
#9 0x6362d177d3e4 <unknown>
#10 0x6362d17813d7 <unknown>
#11 0x6362d178bb20 <unknown>
#12 0x6362d1782023 <unknown>
#13 0x6362d17501aa <unknown>
#14 0x6362d17a66b8 <unknown>
#15 0x6362d17a6847 <unknown>
#16 0x6362d17b6243 <unknown>
#17 0x786b3a894ac3 <unknown>

